// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1068:CancellationToken parameters must come last", Justification = "<Pending>", Scope = "member", Target = "~M:Com.H.Data.Common.AdoNetExt.ExecuteQueryAsync(System.Data.Common.DbCommand,System.String,System.Object,System.String,System.Threading.CancellationToken,System.Boolean)~System.Collections.Generic.IAsyncEnumerable{System.Object}")]
[assembly: SuppressMessage("Design", "CA1068:CancellationToken parameters must come last", Justification = "<Pending>", Scope = "member", Target = "~M:Com.H.Data.Common.AdoNetExt.ExecuteQueryAsyncMain(System.Data.Common.DbCommand,System.String,System.Collections.Generic.IEnumerable{Com.H.Data.Common.QueryParams},System.Threading.CancellationToken,System.Boolean)~System.Collections.Generic.IAsyncEnumerable{System.Object}")]
[assembly: SuppressMessage("Design", "CA1068:CancellationToken parameters must come last", Justification = "<Pending>", Scope = "member", Target = "~M:Com.H.Data.Common.AdoNetExt.ExecuteQueryAsync``1(System.Data.Common.DbConnection,System.String,System.Object,System.String,System.Threading.CancellationToken,System.Nullable{System.Int32},System.Boolean)~System.Collections.Generic.IAsyncEnumerable{``0}")]
[assembly: SuppressMessage("Design", "CA1068:CancellationToken parameters must come last", Justification = "<Pending>", Scope = "member", Target = "~M:Com.H.Data.Common.AdoNetExt.ExecuteQueryAsync``1(System.Data.Common.DbCommand,System.String,System.Object,System.String,System.Threading.CancellationToken,System.Boolean)~System.Collections.Generic.IAsyncEnumerable{``0}")]
[assembly: SuppressMessage("Design", "CA1068:CancellationToken parameters must come last", Justification = "<Pending>", Scope = "member", Target = "~M:Com.H.Data.Common.AdoNetExt.ExecuteQueryAsync``1(System.String,System.String,System.Object,System.String,System.Threading.CancellationToken,System.Nullable{System.Int32},System.Boolean)~System.Collections.Generic.IAsyncEnumerable{``0}")]
[assembly: SuppressMessage("Design", "CA1068:CancellationToken parameters must come last", Justification = "<Pending>", Scope = "member", Target = "~M:Com.H.Data.Common.AdoNetExt.ExecuteQueryAsync(System.Data.Common.DbConnection,System.String,System.Object,System.String,System.Threading.CancellationToken,System.Nullable{System.Int32},System.Boolean)~System.Collections.Generic.IAsyncEnumerable{System.Object}")]
[assembly: SuppressMessage("Design", "CA1068:CancellationToken parameters must come last", Justification = "<Pending>", Scope = "member", Target = "~M:Com.H.Data.Common.AdoNetExt.ExecuteQueryAsync(System.String,System.String,System.Object,System.String,System.Threading.CancellationToken,System.Nullable{System.Int32},System.Boolean)~System.Collections.Generic.IAsyncEnumerable{System.Object}")]
[assembly: SuppressMessage("Design", "CA1068:CancellationToken parameters must come last", Justification = "<Pending>", Scope = "member", Target = "~M:Com.H.Data.Common.AdoNetExt.ExecuteCommandAsyncMain(System.Data.Common.DbCommand,System.String,System.Collections.Generic.IEnumerable{Com.H.Data.Common.QueryParams},System.Threading.CancellationToken,System.Boolean)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1068:CancellationToken parameters must come last", Justification = "<Pending>", Scope = "member", Target = "~M:Com.H.Data.Common.AdoNetExt.ExecuteCommandAsync(System.Data.Common.DbConnection,System.String,System.Object,System.String,System.Threading.CancellationToken,System.Nullable{System.Int32},System.Boolean)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1068:CancellationToken parameters must come last", Justification = "<Pending>", Scope = "member", Target = "~M:Com.H.Data.Common.AdoNetExt.ExecuteCommandAsync(System.Data.Common.DbCommand,System.String,System.Object,System.String,System.Threading.CancellationToken,System.Boolean)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1068:CancellationToken parameters must come last", Justification = "<Pending>", Scope = "member", Target = "~M:Com.H.Data.Common.AdoNetExt.ExecuteCommandAsync(System.String,System.String,System.Object,System.String,System.Threading.CancellationToken,System.Nullable{System.Int32},System.Boolean)~System.Threading.Tasks.Task")]
